name: Build

on:
  push:
    branches:
      - master
      - android-10
  pull_request:
    branches:
      - master
      - android-10
      
jobs:
  build:
    runs-on:
    please wait while i finish later asshole
